/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_linkfeeling_hankserve_bean_NDKTools */

#ifndef _Included_cn_linkfeeling_hankserve_bean_NDKTools
#define _Included_cn_linkfeeling_hankserve_bean_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_linkfeeling_hankserve_bean_NDKTools
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_linkfeeling_hankserve_bean_NDKTools_getStringFromNDK
  (JNIEnv *, jclass);

/*
 * Class:     cn_linkfeeling_hankserve_bean_NDKTools
 * Method:    match_data
 * Signature: ([BLcn/linkfeeling/hankserve/bean/NDKTools/WatchData;)I
 */
JNIEXPORT jint JNICALL Java_cn_linkfeeling_hankserve_bean_NDKTools_match_1data
  (JNIEnv *, jclass, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
